### PR TITLE
Fix: Migrate use of hashValues to Object.hash

### PR DESCRIPTION
**Pull request by shatanikmahanty**
Flutter's latest stable has removed the method hashValues.

This PR fixes that to use Object.hash method

### CODE REVIEW

**Comment by shatanikmahanty** [comment]
@KevinVan720 could you please review this and release a new pub version. It would be very much helpful. Thanks!

**Review by ShqipdonDrenica — APPROVED** [review]

**Comment by JohnSamy11** [comment]
be aware that the dimension: ^0.1.7 package included in the .yaml file also contains the same issue internally @shatanikmahanty

**Comment by shatanikmahanty** [comment]
> be aware that the dimension: ^0.1.7 package included in the .yaml file also contains the same issue internally @shatanikmahanty 

@JohnSamy11 I had also created a PR there, it was merged. Once it will be live in pub.dev. I will update this PR

**Comment by wantroba** [comment]
any prediction of when it will be on pub.dev?

**Comment by KevinVan720** [comment]
@shatanikmahanty Thank you for the PR. I have published a new version for the `dimension` package. I will update the version myself and publish a new version for this package.

**Comment by shatanikmahanty** [comment]
> @shatanikmahanty Thank you for the PR. I have published a new version for the `dimension` package. I will update the version myself and publish a new version for this package. 

Thank you for this ❤️

**Comment by wantroba** [comment]
Tks @shatanikmahanty and @KevinVan720 . Version 2.0.0 works like a charm ❤️

**Pull request merged**
